version: '3.8'
services:
  back:
    container_name: back
    build: ./back
    ports:
      - 8080:8080
  front:
    container_name: front
    build: ./front
    ports:
      - 5173:5173
  db:
    container_name: db
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    ports:
      - 5432:5432