version: '3.8'
services:
  postgres:
    image: postgres:latest
    container_name: db
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - 5432:5432
  
  front:
    build:
      context: ./front
      dockerfile: dockerfile
    container_name: front
    volumes:
      - ./front:/app
      -  /app/node_modules
    working_dir: /app
    ports:
      - 5173:5173

  back:
    build:
      context: ./back
      dockerfile: dockerfile
    container_name: back
    volumes:
      - ./back:/app
      -  /app/node_modules
    working_dir: /app
    ports:
      - 5050:5050
    